# Site wide configuration

title: Elapaint
description: "The Digital Portrait"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://elapaint.github.io/
email: elapaint88@gmail.com

# Jekyll configuration

paginate: 12
paginate_path: "/articles/page:num/"



sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title
markdown: kramdown
highlighter: pygments


gems:
  - jekyll-sitemap
  - jekyll-tagging

 
  
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
ignored_tags: [tags,to,ignore]

# Site owner
owner:
  name: elapaint
  web: http://mademistakes.com
  email: michael@mademistakes.com
  twitter: elapaint
  bio: "Just another girl who love painting and art."
  avatar: bio-photo.png # 160x160 px image for author byline
  google:
    plus: +MichaelRoseDesign
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
    google_analytics_ua: "UA-59843792-1" # Google Analytics site specific id
  disqus-shortname: mooyokii



exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

